### PR TITLE
Revise README.md

### PR DESCRIPTION
**Pull request by sangyun-han**
Revise typing error.
246 line : ,build => .build

### CODE REVIEW

**Comment by sangyun-han** [comment]
Revise entirely READM.md file. No longer needed

**Comment by kuujo** [comment]
Indeed. I'll probably merge the storage-levels branch tomorrow and those README docs will remain

**Comment by sangyun-han** [comment]
Will you merge the storage-levels branch to master branch? 
then the storage-level branch's README will replace the master branch's README. Right?

**Comment by kuujo** [comment]
Yep.

**Pull request closed without merging**
